drop database projetobolo;
CREATE DATABASE PROJETOBOLO;
USE PROJETOBOLO;

CREATE TABLE CLIENTE(
	ID INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    CPF BIGINT NOT NULL unique,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE BIGINT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE FUNCIONARIO(
	ID INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    CPF BIGINT NOT NULL unique,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE BIGINT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE BOLO(
	ID INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    TAMANHO VARCHAR(100) NULL,
    SABOR VARCHAR(100) NULL,
    VALOR NUMERIC(9,2) NULL,
    primary key(ID)
);
CREATE TABLE CATALOGO(
	ID INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    TAMANHO VARCHAR(100) NULL,
    TIPO INT NULL,
    VALOR NUMERIC(9,2) NULL,
    primary key(ID)
);

INSERT INTO CLIENTE(NOME, CPF, ENDERECO, TELEFONE)
VALUES('TIAGO', 123456, 'RUA A, BROTAS', 71888888);
INSERT INTO CLIENTE
VALUES(0, 'DANIEL', 11111, 'RUA B, FG', 71999999);

INSERT INTO FUNCIONARIO(NOME, CPF, ENDERECO, TELEFONE)
VALUES('Jair Messias Bolsonaro', 78945698745, 'RUA A, BROTAS', 71977554466);
INSERT INTO FUNCIONARIO(NOME, CPF, ENDERECO, TELEFONE)
VALUES('Luis Inacio Lula da Silva', 96314785278, 'RUA B, LAPA', 71988779966);

INSERT INTO BOLO(NOME, TAMANHO, SABOR, VALOR)
VALUES('Bolo vulcao', 'Pequeno','Ninho c/ Morango',30);
INSERT INTO BOLO(NOME, TAMANHO, SABOR, VALOR)
VALUES('Bolo vulcao', 'Medio','Mousse de Limão',55);
INSERT INTO BOLO(NOME, TAMANHO, SABOR, VALOR)
VALUES('Bolo vulcao', 'Grande','SONHO DE VALSA',85);

INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Torta decorada', 'Pequeno', 1, 80);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Torta decorada', 'Medio', 1, 120);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Torta decorada', 'Grande', 1, 150);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Torta decorada', 'Familia', 1, 200);

INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Tradicional', 'Pequeno', 2, 30);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Tradicional', 'Medio', 2, 50);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Tradicional', 'Grande', 2, 80);

INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Trufado', 'Pequeno', 3, 35);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Trufado', 'Medio', 3, 60);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo vulcao Trufado', 'Grande', 3, 90);

INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo caseiro', 'Pequeno', 4, 20);
INSERT INTO catalogo(NOME, TAMANHO, TIPO, VALOR)
VALUES('Bolo caseiro', 'Grande', 4, 35);